apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-service
  labels:
    app: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-service
  template:
    metadata:
      labels:
        app: stock-service
    spec:
      containers:
        - name: stock-service
          image: velantechlab/inventory-stock-api:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/stockdb
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
